---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns-openshift-lws-operator.yaml
  - og-openshift-lws-operator.yaml
  - sub-leader-worker-set.yaml

  - leaderworkersetoperator-cluster.yaml
