---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sub-openshift-pipelines-operator.yaml
  - sa-enable-pipelines-plugin.yaml
  - cr-enable-pipelines-plugin.yaml
  - crb-enable-pipelines-plugin.yaml
  - job-enable-pipelines-plugin.yaml