# Default values for rhoai-lls-playground.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Global configuration
global:
  namespace: lls-playground
  clusterDomain: "opentlc.com"

# Application configuration
app:
  image: "quay.io/rh-aiservices-bu/llama-stack-playground:0.2.18"
  defaultModel: "llama-4-scout-17b-16e-w4a16"

# External service configuration
llamaStack:
  endpoint: "http://llama-stack-service:8321"
